USE [master]
GO

/****** Object:  Database [ScholarShip]    Script Date: 09/06/2022 3:04:34 PM ******/
CREATE DATABASE [ScholarShip]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ScholarShip', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLDEV\MSSQL\DATA\ScholarShip.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ScholarShip_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLDEV\MSSQL\DATA\ScholarShip_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ScholarShip].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ScholarShip] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ScholarShip] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ScholarShip] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ScholarShip] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ScholarShip] SET ARITHABORT OFF 
GO

ALTER DATABASE [ScholarShip] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ScholarShip] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ScholarShip] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ScholarShip] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ScholarShip] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ScholarShip] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ScholarShip] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ScholarShip] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ScholarShip] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ScholarShip] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ScholarShip] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ScholarShip] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ScholarShip] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ScholarShip] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ScholarShip] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ScholarShip] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [ScholarShip] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ScholarShip] SET RECOVERY FULL 
GO

ALTER DATABASE [ScholarShip] SET  MULTI_USER 
GO

ALTER DATABASE [ScholarShip] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ScholarShip] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ScholarShip] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ScholarShip] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ScholarShip] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ScholarShip] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ScholarShip] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ScholarShip] SET  READ_WRITE 
GO

